jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build \
              -t $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest \
              --cache-from $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest \
              .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker push $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest
  deploy:
    machine: true
    steps:
      - checkout
      # - run:
      #     name: Remove container
      #     command: |
      #       ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP \
      #       sudo docker kill client && docker rm client

      - run:
          name: Pulling new container
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP \
            sudo docker pull $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest

      - run:
          name: Run the container
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP \
            sudo docker run \
            -e REACT_APP_API_URL=$REACT_APP_API_URL \
            -e REACT_APP_SHOP=$REACT_APP_SHOP \
            -e PORT=$PORT \ 
            --name client -d -i -t -p $PORT:80 $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest
           environment:
            REACT_APP_API_URL: $REACT_APP_API_URL
            REACT_APP_SHOP: $REACT_APP_SHOP
            PORT: $PORT


workflows:
  version: 2
  deploy:
    jobs:
      # - build:
      #     filters:
      #       tags:
      #         only: /^v\d*\.\d*\.\d*$/
      - deploy:
          # requires:
          #   - build
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*$/
