jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build \
              -t $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1  \
              -t $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest \
              --cache-from $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest \
              .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker push $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
            docker push $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest
  deploy:
    # docker:
    #   - image: circleci/node:8.10
    machine: true
    steps:
      - checkout
      - run:
          name: Pulling new container
          command: |
            ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP \
            sudo docker pull $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest
            
      - run:
          name: Run the cotainer
          command: |
            sudo docker ps -a
            sudo docker run --name client -d -i -t -p 4000:80 $DOCKER_REGISTRY/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  version: 2
  deploy:
    jobs:
      # - build:
      #     filters:
      #       tags:
      #         only: /^v\d*\.\d*\.\d*$/
      - deploy:
          # requires:
          #   - build
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*$/
